---
name: CPAN-Dependency
version: 0.07
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Analyzes CPAN modules and generates their dependency tree
license: perl
requires:
  CPANPLUS: 0.053
  DBD::SQLite2: 0
  DBI: 1.0
  File::Slurp: 0
  File::Spec: 0
  Test::Deep: 0
  Test::More: 0
  Test::Warn: 0
  YAML: 0
provides:
  CPAN::Dependency:
    file: lib/CPAN/Dependency.pm
    version: 0.07
generated_by: Module::Build version 0.2609
